theme:
  name: 'material'
  language: 'zh'

repo_name: 'dianliang233/minecraft-lzh'
repo_url: 'https://github.com/dianliang233/minecraft-lzh'
extra:
  social:
    - type: 'github'
      link: 'https://github.com/dianliang233/minecraft-lzh'
google_analytics:
  - 'UA-162014786-1'
  - 'auto'
